#!/usr/bin/php
<?php

include dirname(dirname(__FILE__)).'/app/Config/database.php';

$db_config = new DATABASE_CONFIG('default');

$command = array(
    'mysqldump',
    '-u'.$db_config->default['login'],
    '-p'.$db_config->default['password'],
    '-h'.$db_config->default['host'],
    '-d  --skip-opt',
    $db_config->default['database'],
    ' > 0001_init.sql',
);

$command = implode(' ', $command);

echo "Dumping schema using: {$command}\n";
echo system($command);
echo "Done!";
